from enum import Enum

#     SYSTEM CONSTANTS

SERVER_DATABASE_FILE = "defensive.db"
SERVER_PORT_FILE = "port.info"
DEFAULT_SERVER_PORT = 1357
SERVER_VERSION = 3
BUFFER_SIZE = 1024

#     CRYPTO CONSTANTS

AES_CBC_KEY_SIZE = 16  # 128 bit
PUBLIC_KEY_SIZE = 160

#     SERVER RESPONSE SIZES

CLIENT_ID_SIZE = 16
CONTENT_SIZE = 4
FILENAME_SIZE = 255
CHECKSUM_SIZE = 4


#     SERVER RESPONSE CODES

class ResponseCode(Enum):
    RESPONSE_REGISTRATION_SUCCEEDED = 2100
    RESPONSE_REGISTRATION_FAILED = 2101
    RESPONSE_GOT_PUBLIC_SENDING_AES = 2102
    RESPONSE_FILE_RECEIVED_OK = 2103
    RESPONSE_MESSAGE_RECEIVED = 2104
    RESPONSE_RECONNECT_APPROVED_SENDING_AES = 2105
    RESPONSE_RECONNECT_NOT_APPROVED = 2106
    RESPONSE_GENERAL_ERROR = 2107


#    CLIENT REQUEST SIZES

REQUEST_VERSION_SIZE = 1
REQUEST_CODE_SIZE = 2
REQUEST_PAYLOAD_SIZE_LENGTH = 4

CLIENT_NAME_SIZE = 255

REQUEST_HEADER_SIZE = CLIENT_ID_SIZE + REQUEST_VERSION_SIZE + REQUEST_CODE_SIZE + REQUEST_PAYLOAD_SIZE_LENGTH


#   SERVER REQUEST CODES

class RequestCode(Enum):
    REQUEST_REGISTER = 1025
    REQUEST_SENT_PUBLIC_KEY = 1026
    REQUEST_RECONNECT = 1027
    REQUEST_SEND_FILE = 1028
    REQUEST_CRC_OK = 1029
    REQUEST_CRC_NOT_OK_RESEND_FILE = 1030
    REQUEST_CRC_NOT_OK_ABORT = 1031
